theme = "monokai_pro_machine"

[editor]
bufferline = "multiple"
cursorline = true
color-modes = true
true-color = true
soft-wrap.enable = true
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "separator", "file-name", "file-modification-indicator"]
right = ["file-encoding","spinner", "separator", "diagnostics", "position-percentage"]
separator = " "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "┊"

[keys.normal]
C-pageup = "goto_previous_buffer"
C-pagedown = "goto_next_buffer"
C-j= "goto_previous_buffer"
C-k= "goto_next_buffer"
C-del = ":buffer-close"
C-r = [":config-reload", ":reload-all"]
C-q = ":buffer-close"
"?" = ["move_char_left", "move_next_word_end", "move_prev_word_start", "search_selection", "global_search"]
C-g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w100% -h100% -E lazygit"
C-t = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E bash"
"p" = [":clipboard-paste-after"]
"P" = [":clipboard-paste-before"]
"R" = [":clipboard-paste-replace"]
"y" = [":clipboard-yank"]
"d" = [":clipboard-yank", "delete_selection"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.select]
"p" = [":clipboard-paste-after"]
"P" = [":clipboard-paste-before"]
"R" = [":clipboard-paste-replace"]
"y" = [":clipboard-yank"]
"d" = [":clipboard-yank", "delete_selection"]


[keys.insert]
C-backspace = "delete_word_backward"
